sudo: required
service:
  - docker

before_install:
  - docker build -t ksganesh18/react-test  -f ./client/Dockerfile.dev ./client

script:
  - docker run ksganesh18/react-test npm test -- --coverage

after_success:
  - docker build -t ksganesh18/multi-client ./client
  - docker build -t ksganesh18/multi-nginx ./nginx
  - docker build -t ksganesh18/multi-server ./server
  - docker build -t ksganesh18/multi-worker ./worker

  #Log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  #take the images and push it to docker hub
  - docker push ksganesh18/multi-client
  - docker push ksganesh18/multi-nginx
  - docker push ksganesh18/multi-server
  - docker push ksganesh18/multi-worker